import { Info } from 'lucide-react';

const SANS: React.CSSProperties = { fontFamily: "'Inter', -apple-system, sans-serif" };
const MONO: React.CSSProperties = { fontFamily: "'JetBrains Mono', monospace" };

export default function SystemContextBanner() {
  return (
    <div className="bg-gradient-to-r from-amber-50 to-orange-50 border-y border-amber-200/60">
      <div className="max-w-7xl mx-auto px-6 py-4">
        <div className="flex gap-4">
          <div className="flex-shrink-0 mt-0.5">
            <div className="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center">
              <Info className="w-5 h-5 text-amber-700" />
            </div>
          </div>
          <div className="flex-1">
            <h3 className="text-sm font-bold text-amber-900 mb-2" style={SANS}>
              System Overview: Reinforcement Learning Decision Support
            </h3>
            <p className="text-sm text-amber-800 leading-relaxed mb-3" style={SANS}>
              <strong>Yormetrics</strong> uses a Reinforcement Learning (PPO) agent to recommend optimal class suspension policies based on weather patterns and demographic data. The system learns from historical incidents to suggest early, data-driven decisions.
            </p>
            <div className="bg-white/60 rounded-lg p-3 border border-amber-200/40">
              <p className="text-xs text-amber-900 leading-relaxed" style={SANS}>
                <strong className="text-amber-950">Data Transparency:</strong> Incident dates, PAGASA warnings, and official LGU decisions reflect <span className="font-semibold text-amber-950">factual historical records</span> from NDRRMC announcements. Metrics labeled as <span className="font-mono text-xs bg-amber-100 px-1.5 py-0.5 rounded">Simulated Stranded</span> are <span className="font-semibold text-amber-950">mathematical projections</span> generated by our demographic density models and do not represent actual reported counts.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
